### PR TITLE
Fix a mistake

### PR DESCRIPTION
**Pull request by millerf**
(the controls are available through the  component and not the directive)

### CODE REVIEW

**Comment by sconix** [comment]
Actually it is not a mistake, with the upcoming 4.5.0 release for which I already updated the readme you need to access the api through directiveRef which is available from the componentRef. But maybe I can improve the wording a bit since I can see it not being fully clear.

**Comment by millerf** [comment]
Ah... well...
So you modified the Readme before the code :)
I guess that is fine as long as you pass to v4.5 soon...

**Comment by sconix** [comment]
Well the code has been also modified, it just haven't been released. I will release it today.

**Comment by millerf** [comment]
Perfect. I actually have a problem with nextSlide and prevSlide on previous version.
I hope it will fix them...

**Comment by sconix** [comment]
At least I am not aware of any problems regarding them, they just call the corresponding Swiper functions directly. If its not fixed you can make an issue, but I think that its a bug in Swiper if there is problems with those.

**Pull request closed without merging**
